/* Generated by scripts/generate_c_parser.ts */
/*

 * EXAMPLES:
 *
 * 1. Simple Pattern:
 * {
 *   "name": "Blinky",
 *   "front": {
 *     "pattern": {
 *       "type": "simple",
 *       "name": "Flash",
 *       "duration": 1000,
 *       "changeAt": [
 *         {
 *           "ms": 0,
 *           "output": "#FF0000"
 *         },
 *         {
 *           "ms": 500,
 *           "output": "#000000"
 *         }
 *       ]
 *     }
 *   }
 * }
 *
 * 2. Equation Pattern:
 * {
 *   "name": "Sine Wave",
 *   "case": {
 *     "pattern": {
 *       "type": "equation",
 *       "name": "Red Sine",
 *       "duration": 2000,
 *       "red": {
 *         "sections": [
 *           {
 *             "equation": "sin(t * 2 * pi)",
 *             "duration": 2000
 *           }
 *         ],
 *         "loopAfterDuration": true
 *       },
 *       "green": {
 *         "sections": [],
 *         "loopAfterDuration": true
 *       },
 *       "blue": {
 *         "sections": [],
 *         "loopAfterDuration": true
 *       }
 *     }
 *   }
 * }
 *
 * 3. Accel Trigger:
 * {
 *   "name": "Impact",
 *   "front": {
 *     "pattern": {
 *       "type": "simple",
 *       "name": "Steady Off",
 *       "duration": 1000,
 *       "changeAt": [
 *         {
 *           "ms": 0,
 *           "output": "#000000"
 *         }
 *       ]
 *     }
 *   },
 *   "accel": {
 *     "triggers": [
 *       {
 *         "threshold": 50,
 *         "front": {
 *           "pattern": {
 *             "type": "simple",
 *             "name": "White Flash",
 *             "duration": 100,
 *             "changeAt": [
 *               {
 *                 "ms": 0,
 *                 "output": "#FFFFFF"
 *               }
 *             ]
 *           }
 *         }
 *       }
 *     ]
 *   }
 * }

 */
#ifndef MODE_MODEL_H
#define MODE_MODEL_H

#include <stdint.h>
#include <stdbool.h>

typedef enum {
    PATTERN_TYPE_SIMPLE,
    PATTERN_TYPE_EQUATION
} PatternType;

typedef enum SimpleOutputType {
	BULB,
	RGB
} SimpleOutputType;

typedef enum BulbSimpleOutput {
	low, high
} BulbSimpleOutput;

typedef struct RGBSimpleOutput RGBSimpleOutput;
typedef struct SimpleOutput SimpleOutput;

typedef struct PatternChange PatternChange;
typedef struct SimplePattern SimplePattern;
typedef struct EquationSection EquationSection;
typedef struct ChannelConfig ChannelConfig;
typedef struct EquationPattern EquationPattern;
typedef struct ModePattern ModePattern;
typedef struct ModeComponent ModeComponent;
typedef struct ModeAccelTrigger ModeAccelTrigger;
typedef struct ModeAccel ModeAccel;
typedef struct Mode Mode;

struct RGBSimpleOutput {
	uint8_t r; // 0 - 255
	uint8_t g; // 0 - 255
	uint8_t b; // 0 - 255
};

struct SimpleOutput {
	SimpleOutputType type;
	union {
		BulbSimpleOutput bulb;
		RGBSimpleOutput rgb;
	} data;
};

struct PatternChange {
    uint32_t ms;
    SimpleOutput output;
};

struct SimplePattern {
    char name[32];
    uint32_t duration;
    PatternChange changeAt[32];
    uint8_t changeAt_count;
};

struct EquationSection {
    char equation[64];
    uint32_t duration;
};

struct ChannelConfig {
    EquationSection sections[3];
    uint8_t sections_count;
    bool loopAfterDuration;
};

struct EquationPattern {
    char name[32];
    uint32_t duration;
    ChannelConfig red;
    ChannelConfig green;
    ChannelConfig blue;
};

struct ModePattern {
    PatternType type;
    union {
        SimplePattern simple;
        EquationPattern equation;
    } data;
};

struct ModeComponent {
    ModePattern pattern;
};

struct ModeAccelTrigger {
    uint8_t threshold;
    ModeComponent front;
    bool has_front;
    ModeComponent case_comp;
    bool has_case_comp;
};

struct ModeAccel {
    ModeAccelTrigger triggers[2];
    uint8_t triggers_count;
};

struct Mode {
    char name[32];
    ModeComponent front;
    bool has_front;
    ModeComponent case_comp;
    bool has_case_comp;
    ModeAccel accel;
    bool has_accel;
};

#endif // MODE_MODEL_H
