import type { Metadata } from "next";
import { Providers } from "./providers";
import { NoSSR } from "./NoSSR";
import ErudaWrapper from "./ErudaWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NoSSR>
          <ErudaWrapper />
        </NoSSR>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
