/* Generated by scripts/generate_c_parser.cjs */
#ifndef MODE_PARSER_H
#define MODE_PARSER_H

#include <stdint.h>
#include <stdbool.h>
#include "lwjson/lwjson.h"

typedef enum {
    PATTERN_TYPE_SIMPLE,
    PATTERN_TYPE_EQUATION
} PatternType;

typedef struct PatternChange PatternChange;
typedef struct SimplePattern SimplePattern;
typedef struct EquationSection EquationSection;
typedef struct ChannelConfig ChannelConfig;
typedef struct EquationPattern EquationPattern;
typedef struct ModePattern ModePattern;
typedef struct ModeComponent ModeComponent;
typedef struct ModeAccelTrigger ModeAccelTrigger;
typedef struct ModeAccel ModeAccel;
typedef struct Mode Mode;

struct PatternChange {
    uint32_t ms;
    char output[8];
};

struct SimplePattern {
    char name[32];
    uint32_t duration;
    PatternChange changeAt[64];
    uint8_t changeAt_count;
};

struct EquationSection {
    char equation[64];
    uint32_t duration;
};

struct ChannelConfig {
    EquationSection sections[8];
    uint8_t sections_count;
    bool loopAfterDuration;
};

struct EquationPattern {
    char id[37];
    bool has_id;
    char name[32];
    uint32_t duration;
    ChannelConfig red;
    ChannelConfig green;
    ChannelConfig blue;
};

struct ModePattern {
    PatternType type;
    union {
        SimplePattern simple;
        EquationPattern equation;
    } data;
};

struct ModeComponent {
    ModePattern pattern;
};

struct ModeAccelTrigger {
    uint32_t threshold;
    ModeComponent front;
    bool has_front;
    ModeComponent case_comp;
    bool has_case_comp;
};

struct ModeAccel {
    ModeAccelTrigger triggers[8];
    uint8_t triggers_count;
};

struct Mode {
    char name[32];
    ModeComponent front;
    bool has_front;
    ModeComponent case_comp;
    bool has_case_comp;
    ModeAccel accel;
    bool has_accel;
};

bool parseMode(lwjson_t *lwjson, lwjson_token_t *token, Mode *out);

#endif // MODE_PARSER_H
