/* Generated by scripts/generate_c_parser.ts */
/*

 * EXAMPLES:
 *
 * 1. Simple Pattern:
 * {
 *   "name": "Blinky",
 *   "front": {
 *     "pattern": {
 *       "type": "simple",
 *       "name": "Flash",
 *       "duration": 1000,
 *       "changeAt": [
 *         {
 *           "ms": 0,
 *           "output": "#FF0000"
 *         },
 *         {
 *           "ms": 500,
 *           "output": "#000000"
 *         }
 *       ]
 *     }
 *   }
 * }
 *
 * 2. Equation Pattern:
 * {
 *   "name": "Sine Wave",
 *   "case": {
 *     "pattern": {
 *       "type": "equation",
 *       "name": "Red Sine",
 *       "duration": 2000,
 *       "red": {
 *         "sections": [
 *           {
 *             "equation": "sin(t * 2 * pi)",
 *             "duration": 2000
 *           }
 *         ],
 *         "loopAfterDuration": true
 *       },
 *       "green": {
 *         "sections": [],
 *         "loopAfterDuration": true
 *       },
 *       "blue": {
 *         "sections": [],
 *         "loopAfterDuration": true
 *       }
 *     }
 *   }
 * }
 *
 * 3. Accel Trigger:
 * {
 *   "name": "Impact",
 *   "front": {
 *     "pattern": {
 *       "type": "simple",
 *       "name": "Steady Off",
 *       "duration": 1000,
 *       "changeAt": [
 *         {
 *           "ms": 0,
 *           "output": "#000000"
 *         }
 *       ]
 *     }
 *   },
 *   "accel": {
 *     "triggers": [
 *       {
 *         "threshold": 2000,
 *         "front": {
 *           "pattern": {
 *             "type": "simple",
 *             "name": "White Flash",
 *             "duration": 100,
 *             "changeAt": [
 *               {
 *                 "ms": 0,
 *                 "output": "#FFFFFF"
 *               }
 *             ]
 *           }
 *         }
 *       }
 *     ]
 *   }
 * }

 */
#ifndef MODE_PARSER_H
#define MODE_PARSER_H

#include <stdint.h>
#include <stdbool.h>
#include "lwjson/lwjson.h"

typedef enum {
    MODE_PARSER_OK = 0,
    MODE_PARSER_ERR_MISSING_FIELD,
    MODE_PARSER_ERR_STRING_TOO_SHORT,
    MODE_PARSER_ERR_VALUE_TOO_SMALL,
    MODE_PARSER_ERR_ARRAY_TOO_SHORT,
    MODE_PARSER_ERR_INVALID_VARIANT,
    MODE_PARSER_ERR_VALIDATION_FAILED
} ModeParserError;

typedef struct {
    ModeParserError error;
    char path[128];
} ModeErrorContext;

const char* modeParserErrorToString(ModeParserError err);

typedef enum {
    PATTERN_TYPE_SIMPLE,
    PATTERN_TYPE_EQUATION
} PatternType;

typedef struct PatternChange PatternChange;
typedef struct SimplePattern SimplePattern;
typedef struct EquationSection EquationSection;
typedef struct ChannelConfig ChannelConfig;
typedef struct EquationPattern EquationPattern;
typedef struct ModePattern ModePattern;
typedef struct ModeComponent ModeComponent;
typedef struct ModeAccelTrigger ModeAccelTrigger;
typedef struct ModeAccel ModeAccel;
typedef struct Mode Mode;

struct PatternChange {
    uint32_t ms;
    char output[8];
};

struct SimplePattern {
    char name[32];
    uint32_t duration;
    PatternChange changeAt[64];
    uint8_t changeAt_count;
};

struct EquationSection {
    char equation[64];
    uint32_t duration;
};

struct ChannelConfig {
    EquationSection sections[8];
    uint8_t sections_count;
    bool loopAfterDuration;
};

struct EquationPattern {
    char name[32];
    uint32_t duration;
    ChannelConfig red;
    ChannelConfig green;
    ChannelConfig blue;
};

struct ModePattern {
    PatternType type;
    union {
        SimplePattern simple;
        EquationPattern equation;
    } data;
};

struct ModeComponent {
    ModePattern pattern;
};

struct ModeAccelTrigger {
    uint32_t threshold;
    ModeComponent front;
    bool has_front;
    ModeComponent case_comp;
    bool has_case_comp;
};

struct ModeAccel {
    ModeAccelTrigger triggers[8];
    uint8_t triggers_count;
};

struct Mode {
    char name[32];
    ModeComponent front;
    bool has_front;
    ModeComponent case_comp;
    bool has_case_comp;
    ModeAccel accel;
    bool has_accel;
};

ModeParserError parseMode(lwjson_t *lwjson, lwjson_token_t *token, Mode *out, ModeErrorContext *ctx);

#endif // MODE_PARSER_H
