/* Generated by scripts/generate_c_parser.ts */
#ifndef INC_JSON_MODE_PARSER_H_
#define INC_JSON_MODE_PARSER_H_

#include "lwjson/lwjson.h"
#include "microlight/json/parser.h"
#include "microlight/model/mode.h"

bool parseMode(lwjson_t *lwjson, lwjson_token_t *token, Mode *out, ParserErrorContext *ctx);

#endif /* INC_JSON_MODE_PARSER_H_ */
