/* Generated by scripts/generate_c_parser.ts */
#ifndef MODE_PARSER_H
#define MODE_PARSER_H

#include "microlight/json/parser.h"
#include "lwjson/lwjson.h"
#include "microlight/model/mode.h"

bool parseMode(lwjson_t *lwjson, lwjson_token_t *token, Mode *out, ParserErrorContext *ctx);

#endif  // MODE_PARSER_H
